services:
  fhir:
    container_name: fhir
    image: hapiproject/hapi:latest
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yml
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hapi
    volumes:
      - ./hapi.postgres.data:/var/lib/postgresql/data

configs:
  hapi:
    file: ./application.yml